dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: gohttps
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: mavenqs
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: pa-emailchat
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.15
- name: pa-emailparser
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: pa-nattydate
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.7
- name: pa-recurrent-nattydatetime
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
- name: pa-scheduler-kue-rediscluster
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.27
